### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by JingyuanHe1222** [larsgottesbueren/gp-ann#3]
Hi, I want to check if I could get a more specific build instructions. I clone the repo; clone the external libraries and check out the correct commits by `git submodule update --init --recursive`
Also I modified hnswlib as instructed. However, when I compile by running the build.py file, specifically when doing `make -j`, I got a bunch of errors, some error log are attached as the following: 
It seems like some libraries are messed up (I checked by git pull and the version on my end is up to date though). 
There's also some error ocurring from building KaMinPar as well. I checked the dependency of KaMinPar and they are all supported. 
I wonder if there's any possible installation steps that I missed? It seems weird that I got some many errors upon building from sourc. 
Thanks in advance!!
```
/home/jingyuah/gp-ann/src/defs.h: In member function ‘double Timer::ElapsedRunning()’:
/home/jingyuah/gp-ann/src/defs.h:92:34: error: ‘runtime_error’ is not a member of ‘std’
         if (!running) throw std::runtime_error("Timer not running but called Restart()");

/home/jingyuah/gp-ann/src/shard_searches.h:22:5: note: ‘std::string’ is defined in header ‘<string>’; did you forget to ‘#include <string>’?
/home/jingyuah/gp-ann/src/shard_searches.h:4:1:
+#include <string>
 
/home/jingyuah/gp-ann/src/shard_searches.h:22:5:
     std::string Serialize() const;
     ^~~
/home/jingyuah/gp-ann/src/shard_searches.h:24:36: error: ‘std::ifstream’ has not been declared
     static ShardSearch Deserialize(std::ifstream& in);


/home/jingyuah/gp-ann/src/points_io.cpp:119:21: error: ‘const string’ {aka ‘const class std::__cxx11::basic_string<char>’} has no member named ‘ends_with’
     } else if (path.ends_with(".i8bin")) {
                     ^~~~~~~~~

make[2]: *** [CMakeFiles/AnalyzeApproximationLosses.dir/build.make:118: CMakeFiles/AnalyzeApproximationLosses.dir/src/kmeans.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:541: CMakeFiles/AnalyzeApproximationLosses.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/Convert.dir/build.make:118: CMakeFiles/Convert.dir/src/kmeans.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:409: CMakeFiles/Convert.dir/all] Error 2
make[2]: *** [CMakeFiles/SmallScaleQueries.dir/build.make:118: CMakeFiles/SmallScaleQueries.dir/src/kmeans.cpp.o] Error 1
make[2]: *** [CMakeFiles/OracleRecall.dir/build.make:118: CMakeFiles/OracleRecall.dir/src/kmeans.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:488: CMakeFiles/OracleRecall.dir/all] Error 2
make[2]: *** [CMakeFiles/QueryAttribution.dir/build.make:118: CMakeFiles/QueryAttribution.dir/src/kmeans.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:462: CMakeFiles/QueryAttribution.dir/all] Error 2
...
make[1]: *** [CMakeFiles/Makefile2:383: CMakeFiles/SmallScaleQueries.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:593: external/KaMinPar/kaminpar-shm/CMakeFiles/kaminpar_shm.dir/all] Error 2
```

**Comment by larsgottesbueren** [comment]
Hi Jingyuan,

What compiler and version are you using?  I'm not able to reproduce the issue (tested 2 compilers x 2 versions). Running the build script works fine for me on a fresh clone.
Still, the errors you show are correct based on just the included files in the headers. I think one reason why it works for me but not for you, could be that the translation units have the needed headers included in some other place, so maybe it depends on some ordering whether or not it works. Since I can't reproduce it and this needs multiple iterations, I think the best course of action is for you to try and add the suggested includes. Happy to take a pull request if you get it working. Also try just `make Partition`, the `build.py` can be a bit spammy :)

Best,
Lars
